name: CI (Self-Hosted)

on:
  workflow_dispatch:

jobs:
  run-local:
    runs-on: self-hosted

    steps:
      - name: 1. Завантаження коду
        uses: actions/checkout@v4

      - name: 2. Перевірка Python
        run: python --version

      - name: 3. Встановлення залежностей
        run: pip install pandas matplotlib seaborn

      - name: 4. Підготовка даних і запуск візуалізації
        shell: cmd
        run: |
          if not exist "artifacts\visualization" mkdir "artifacts\visualization"
          if not exist "data\raw" mkdir "data\raw"
          
          echo Створюємо файл через Python...
          python -c "with open('data/raw/reestrtz01.01.2026.csv', 'w', encoding='utf-8') as f: f.write('BRAND;MAKE;MAKE_YEAR;COLOR;FUEL\nTOYOTA;CAMRY;2020;БІЛИЙ;БЕНЗИН\n')"
          
          echo Запускаємо скрипт...
          python src\visualization.py > artifacts\visualization\run.log 2>&1 || (type artifacts\visualization\run.log & exit 1)

      - name: 5. Збереження результатів
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: result-selfhosted-visualization
          path: |
            artifacts/visualization/
            reports/figures/
          if-no-files-found: ignore