name: CI (Self-Hosted)

on:
  workflow_dispatch:

jobs:
  run-local:
    runs-on: self-hosted

    steps:
      - name: 1. Завантаження коду
        uses: actions/checkout@v4

      - name: 2. Перевірка Python
        run: python --version

      - name: 3. Встановлення залежностей
        run: python -m pip install pandas matplotlib seaborn

      - name: 4. Підготовка даних і запуск візуалізації
        shell: cmd
        run: |
          if not exist "artifacts\visualization" mkdir "artifacts\visualization"
          
          echo Запускаємо скрипт...
          python src\visualization.py > artifacts\visualization\run.log 2>&1 || (type artifacts\visualization\run.log & exit 1)

      - name: 5. Збереження результатів
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: result-selfhosted-visualization
          path: |
            artifacts/visualization/
            reports/figures/
          if-no-files-found: ignore